version: '3.8'
services:

  nodejs:
    image: node:lts-alpine
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./api:/home/node/api
#      - /home/node/api/node_modules
    working_dir: /home/node/api
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://root:password@postgres/app
      - JWT_SECRET=secret
    container_name: moto-rc-api
    command: sh -c "npm install && npm run dev"

  vue:
    image: node:lts-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./front:/home/node/front
#      - /home/node/front/node_modules
    working_dir: /home/node/front
    container_name: moto-rc-front
    environment:
      - PORT=3000
    command: sh -c "npm install && npm run dev"

  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

volumes:
  postgres-data: { }